# Generated by Django 6.0.2 on 2026-03-04 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_0003_booking_owner_0003_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
