# Generated by Django 6.0.2 on 2026-03-04 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_booking_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('court_number', models.PositiveSmallIntegerField()),
                ('surface', models.CharField(choices=[('hard', 'Hard'), ('clay', 'Clay'), ('grass', 'Grass')], default='hard', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time', 'court_number'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'date', 'start_time', 'court_number'), name='unique_saved_slot_per_user')],
            },
        ),
    ]
